/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { Container } from "@material-ui/core";
import { useEffect, useState } from "react";
import { fetchNews, fetchNewsByQuery } from "../pages/api/news";
import { News, Header } from "../components";

export default function Home() {
  const [news, setNews] = useState([]);
  const [selectedCategory, setSelectedCategory] = useState("");
  const [searchQuery, setSearchQuery] = useState("");

  const handleSearch = async (e) => {
    e.preventDefault();
    const data = await fetchNewsByQuery(searchQuery);
    setNews(data);
  };

  useEffect(() => {
    async function fetch() {
      const data = await fetchNews(selectedCategory);
      setNews(data);
      console.log(data);
    }
    fetch();
  }, [selectedCategory]);
  return (
    <Container
      style={{ backgroundColor: "#EDEEF0", maxWidth: "100%", padding: "0" }}
    >
      <Head>
        <title>Indonesian and World News Aggregator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        selectedCategory={selectedCategory}
        setSelectedCategory={setSelectedCategory}
        setSearchQuery={setSearchQuery}
        searchQuery={searchQuery}
        handleSearch={handleSearch}
      />
      <Container fluid="true" style={{ maxWidth: "660px", padding: 0 }}>
        <News news={news} style={{ width: "100%" }} />
      </Container>
    </Container>
  );
}
