/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { Container, Grid, Link, Typography } from "@material-ui/core";
import { useEffect, useState } from "react";
import { fetchNews } from "../pages/api/news";
import { News, Header } from "../components";

export default function Home() {
    const [news, setNews] = useState([]);
    useEffect(() => {
        async function fetch() {
            const data = await fetchNews();
            setNews(data);
            console.log(data);
        }
        fetch();
    }, [news]);

    return (
        <>
            <Head>
                <title>Indonesian Sport News Aggregator</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Container fluid="true" style={{ maxWidth: "1084px" }}>
                <News news={news} />

                <footer>Created by Fadhil Radhian</footer>
            </Container>
        </>
    );
}
